version: '1'
networks:
  immo.net:
    driver: bridge
services:

  immo.api:
    image: 'canals/php:latest'
    environment:
      MYSQL_HOST: ${DB_HOST:-immo.db}
      MYSQL_DATABASE: ${DB_DATABASE:-immo_db}
      MYSQL_USER: ${DB_USER_NAME:-immo_user}
      MYSQL_PASSWORD: ${DB_USER_PASSWD:-immo_password}
    ports:
      - "${SERVER_PORT:-2080}:80"
    volumes:
      - ./api/public/:/var/www/html
      - ./api/:/var/www
    working_dir: /var/www/
    networks:
      - immo.net
    depends_on:
      - immo.db

  immo.adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    networks:
      - immo.net


  immo.db:
    image: 'mysql:latest'
    environment:
      MYSQL_USER: ${DB_USER_NAME:-immo_user}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD:-immo_password}
      MYSQL_DATABASE: ${DB_DATABASE:-immo_db}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD:-immo_root_password}
    networks:
      - immo.net

  immo.client:
    build:
      context: ./front_client
      dockerfile: Dockerfile
    volumes:
      - ./front_client/:/app
      - /app/node_modules
    ports:
      - "${DEV_SERVER_PORT:-3000}:3000"
    working_dir: /app
    environment:
      VUE_APP_API_URL: http://localhost:2080/api
    networks:
      - immo.net
    depends_on:
      - immo.api

  immo.admin:
    build:
      context: ./front_admin
      dockerfile: Dockerfile
    volumes:
      - ./front_admin/:/app
      - /app/node_modules
    ports:
      - "${DEV_SERVER_PORT:-3030}:3000"
    working_dir: /app
    environment:
      VUE_APP_API_URL: http://localhost:2080/api
    networks:
      - immo.net
    depends_on:
      - immo.api
